### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by naiwaaa** [trungbkit/trungbkit.github.io#1]
Chơi sao zọ? OvO

**Comment by trungbkit** [comment]
> Chơi sao zọ? OvO

**Comment by trungbkit** [comment]
> Chơi sao zọ? OvO

Thi hackathon blockchain, mà chưa có smart contract 🤣

**Comment by naiwaaa** [comment]
ghiaaaa =))))) 👍 👍 👍
